### ISSUE TITLE
AttributeError: 'RunTarget' object has no attribute 'sources'

### ISSUE THREAD

**Issue by armangithub** [prozum/meson-cmake-wrapper#1]
Hi, I have an issue running the wrapper with meson: 0.47.1 and CLion

Traceback (most recent call last):
  File "/usr/local/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 379, in main
    return run(sys.argv[1:], launcher)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 287, in run
    return mintro.run(remaining_args)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mintro.py", line 235, in run
    list_target_files(options.target_files, coredata, builddata)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mintro.py", line 117, in list_target_files
    sources = t.sources + t.extra_files
AttributeError: 'RunTarget' object has no attribute 'sources'

Which version of meson should I use ?

**Comment by overby-me** [comment]
Sorry for the late answer.  (I was not on the watch list for the project) I think the issue should be solved by the newest version of meson-cmake-wrapper. If not then open a new issue. The next time I will respond faster. ;)
