### ISSUE TITLE
VSCode:The connection to cmake-server was terminated unexpectedly

### ISSUE THREAD

**Issue by darkoverlordofdata** [prozum/meson-cmake-wrapper#14]
This is on linux, elementaryos. It creates a healthy build folder - i can cd build and run ninja manually, and it works. But via cmake-tools, only the config step works. When I click on build, it fails.

**console:**

[cms-client] Configuring using the "Ninja" CMake generator
[cms-client] Configuring using the "Ninja" CMake generator
[cmake] Configuring done
[cmake] Generating done
[cms-client] The connection to cmake-server was terminated unexpectedly
[cms-client] cmake-server exited with status 1 (null)

**meson-cmake-wrapper.log:**

2019-03-02 14:30:26,045 - CMake Wrapper: (build_dir) "/home/bruce/Documents/GitHub/bing-wall/build"
2019-03-02 14:30:26,046 - CMake Wrapper: (generator) "Ninja"
2019-03-02 14:30:26,047 - CMake Wrapper: (source_dir) "/home/bruce/Documents/GitHub/bing-wall"
2019-03-02 14:30:28,672 - Meson: (project info) "{"name": "com.github.darkoverlordofdata.bing-wall", "version": "0.0.1", "subprojects": []}
"
2019-03-02 14:30:28,673 - Server: handshake (reply) "{'inReplyTo': 'handshake', 'type': 'reply', 'cookie': '0.3220713605062011'}"
2019-03-02 14:30:28,674 - Server: running on "/tmp/cmake-server-0.1398527738120452"
2019-03-02 14:30:28,675 - Server: received (globalSettings) "{'type': 'globalSettings', 'cookie': '0.6999193023407659'}"
2019-03-02 14:30:28,675 - Server: globalSettings (reply) "{'inReplyTo': 'globalSettings', 'type': 'reply', 'capabilities': {'generators': [{'name': 'Ninja', 'platformSupport': False, 'toolsetSupport': False, 'extraGenerators': ['CodeBlocks']}, {'name': 'Unix Makefiles', 'platformSupport': False, 'toolsetSupport': False, 'extraGenerators': ['CodeBlocks']}], 'serverMode': True, 'version': {'isDirty': False, 'major': 3, 'minor': 10, 'patch': 0, 'string': '3.10.0', 'suffix': ''}}, 'buildDirectory': '/home/bruce/Documents/GitHub/bing-wall/build', 'sourceDirectory': '/home/bruce/Documents/GitHub/bing-wall', 'generator': 'Ninja', 'checkSystemVars': False, 'debugOutput': False, 'extraGenerator': '', 'trace': False, 'traceExpand': False, 'warnUninitialized': False, 'warnUnused': False, 'warnUnusedCli': True, 'cookie': '0.6999193023407659'}"
2019-03-02 14:30:28,682 - Server: closing connection
2019-03-02 14:30:29,743 - CMake Wrapper: (build_dir) "/home/bruce/Documents/GitHub/bing-wall/build"
2019-03-02 14:30:29,744 - CMake Wrapper: (generator) "Ninja"
2019-03-02 14:30:29,745 - CMake Wrapper: (source_dir) "/home/bruce/Documents/GitHub/bing-wall"
2019-03-02 14:30:29,745 - CMake Wrapper: (source_dir) "/home/bruce/Documents/GitHub/bing-wall"
2019-03-02 14:30:29,746 - CMake Wrapper: (generator) "Ninja"
2019-03-02 14:30:29,746 - Server: handshake (reply) "{'inReplyTo': 'handshake', 'type': 'reply', 'cookie': '0.9929693645487792'}"
2019-03-02 14:30:29,746 - Server: running on "/tmp/cmake-server-0.4475052761624283"
2019-03-02 14:30:29,748 - Server: received (globalSettings) "{'type': 'globalSettings', 'cookie': '0.46760547906222016'}"
2019-03-02 14:30:29,749 - Server: globalSettings (reply) "{'inReplyTo': 'globalSettings', 'type': 'reply', 'capabilities': {'generators': [{'name': 'Ninja', 'platformSupport': False, 'toolsetSupport': False, 'extraGenerators': ['CodeBlocks']}, {'name': 'Unix Makefiles', 'platformSupport': False, 'toolsetSupport': False, 'extraGenerators': ['CodeBlocks']}], 'serverMode': True, 'version': {'isDirty': False, 'major': 3, 'minor': 10, 'patch': 0, 'string': '3.10.0', 'suffix': ''}}, 'buildDirectory': '/home/bruce/Documents/GitHub/bing-wall/build', 'sourceDirectory': '/home/bruce/Documents/GitHub/bing-wall', 'generator': 'Ninja', 'checkSystemVars': False, 'debugOutput': False, 'extraGenerator': '', 'trace': False, 'traceExpand': False, 'warnUninitialized': False, 'warnUnused': False, 'warnUnusedCli': True, 'cookie': '0.46760547906222016'}"
2019-03-02 14:30:30,068 - Server: received (configure) "{'type': 'configure', 'cacheArguments': ['--no-warn-unused-cli', '-DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-6.0', '-DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-6.0', '-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE', '-DCMAKE_BUILD_TYPE:STRING=Debug'], 'cookie': '0.11012570947538469'}"
2019-03-02 14:30:30,069 - CMake Wrapper: (build_type) "Debug"
2019-03-02 14:30:30,069 - Server: configure (progress) "{'inReplyTo': 'configure', 'type': 'progress', 'progressCurrent': 1000, 'progressMaximum': 1000, 'progressMessage': 0, 'progressMinimum': 0, 'cookie': '0.11012570947538469'}"
2019-03-02 14:30:30,069 - Server: configure (message) "{'type': 'message', 'message': 'Configuring done', 'inReplyTo': 'configure', 'cookie': '0.11012570947538469'}"
2019-03-02 14:30:30,069 - Server: configure (reply) "{'inReplyTo': 'configure', 'type': 'reply', 'cookie': '0.11012570947538469'}"
2019-03-02 14:30:30,071 - Server: received (compute) "{'type': 'compute', 'cookie': '0.963485767989815'}"
2019-03-02 14:30:30,072 - Server: compute (progress) "{'inReplyTo': 'compute', 'type': 'progress', 'progressCurrent': 1000, 'progressMaximum': 1000, 'progressMessage': 0, 'progressMinimum': 0, 'cookie': '0.963485767989815'}"
2019-03-02 14:30:30,073 - Server: compute (message) "{'type': 'message', 'message': 'Generating done', 'inReplyTo': 'compute', 'cookie': '0.963485767989815'}"
2019-03-02 14:30:30,073 - Server: compute (reply) "{'inReplyTo': 'compute', 'type': 'reply', 'cookie': '0.963485767989815'}"
2019-03-02 14:30:30,076 - Server: received (cmakeInputs) "{'type': 'cmakeInputs', 'cookie': '0.11362716377872029'}"
2019-03-02 14:30:30,077 - Server: cmakeInputs (reply) "{'inReplyTo': 'cmakeInputs', 'type': 'reply', 'buildFiles': [{'sources': 'CMakeLists.txt', 'isCMake': False, 'isTemporary': False}], 'cmakeRootDirectory': '/usr/share/cmake', 'sourceDirectory': '/home/bruce/Documents/GitHub/bing-wall', 'cookie': '0.11362716377872029'}"
2019-03-02 14:30:30,079 - Server: received (cache) "{'type': 'cache', 'cookie': '0.8149567908835431'}"
2019-03-02 14:30:30,080 - Server: cache (reply) "{'inReplyTo': 'cache', 'type': 'reply', 'cache': [{'key': 'CMAKE_PROJECT_NAME', 'value': 'com.github.darkoverlordofdata.bing-wall', 'type': 'STATIC', 'properties': {}}, {'key': 'CMAKE_ROOT', 'value': '/home/bruce/.local/bin', 'type': 'INTERNAL', 'properties': {}}, {'key': 'COM.GITHUB.DARKOVERLORDOFDATA.BING-WALL_SOURCE_DIR', 'value': '/home/bruce/Documents/GitHub/bing-wall', 'type': 'STATIC', 'properties': {}}, {'key': 'CMAKE_EXPORT_COMPILE_COMMANDS', 'value': 'TRUE', 'type': 'BOOL', 'properties': {}}, {'key': 'CMAKE_RANLIB', 'value': '/usr/bin/ranlib', 'type': 'FILEPATH', 'properties': {}}, {'key': 'CMAKE_CACHEFILE_DIR', 'value': '/home/bruce/Documents/GitHub/bing-wall/build', 'type': 'INTERNAL', 'properties': {}}, {'key': 'CMAKE_INSTALL_PREFIX', 'value': '/usr/local', 'type': 'PATH', 'properties': {}}, {'key': 'CMAKE_MAKE_PROGRAM', 'value': '/usr/bin/make', 'type': 'FILEPATH', 'properties': {}}, {'key': 'CMAKE_CACHE_MAJOR_VERSION', 'value': '3', 'type': 'INTERNAL', 'properties': {}}, {'key': 'CMAKE_COMMAND', 'value': '/home/bruce/.local/bin/mcw', 'type': 'INTERNAL', 'properties': {}}, {'key': 'CMAKE_C_COMPILER', 'value': '/usr/bin/clang-6.0', 'type': 'FILEPATH', 'properties': {}}, {'key': 'CMAKE_HOME_DIRECTORY', 'value': '/home/bruce/Documents/GitHub/bing-wall', 'type': 'INTERNAL', 'properties': {}}, {'key': 'CMAKE_GENERATOR', 'value': 'Ninja', 'type': 'INTERNAL', 'properties': {}}, {'key': 'CMAKE_CACHE_PATCH_VERSION', 'value': '0', 'type': 'INTERNAL', 'properties': {}}, {'key': 'COM.GITHUB.DARKOVERLORDOFDATA.BING-WALL_BINARY_DIR', 'value': '/home/bruce/Documents/GitHub/bing-wall/build', 'type': 'STATIC', 'properties': {}}, {'key': 'CMAKE_AR', 'value': '/usr/bin/ar', 'type': 'FILEPATH', 'properties': {}}, {'key': 'CMAKE_CACHE_MINOR_VERSION', 'value': '10', 'type': 'INTERNAL', 'properties': {}}, {'key': 'CMAKE_CXX_COMPILER', 'value': '/usr/bin/clang++-6.0', 'type': 'FILEPATH', 'properties': {}}, {'key': 'CMAKE_BUILD_TYPE', 'value': 'Debug', 'type': 'STRING', 'properties': {}}], 'cookie': '0.8149567908835431'}"
2019-03-02 14:30:30,081 - Server: received (codemodel) "{'type': 'codemodel', 'cookie': '0.5096773580252782'}"
2019-03-02 14:30:31,139 - Meson: (project info) "{"name": "com.github.darkoverlordofdata.bing-wall", "version": "0.0.1", "subprojects": []}
"
2019-03-02 14:30:31,644 - Meson: (targets) "[{"name": "com.github.darkoverlordofdata.bing-wall.desktop_data_merge", "id": "com.github.darkoverlordofdata.bing-wall.desktop_data_merge@cus", "filename": "data/com.github.darkoverlordofdata.bing-wall.desktop", "type": "custom", "installed": true, "install_filename": "/usr/local/share/applications/com.github.darkoverlordofdata.bing-wall.desktop", "build_by_default": false}, {"name": "com.github.darkoverlordofdata.bing-wall.appdata.xml_data_merge", "id": "com.github.darkoverlordofdata.bing-wall.appdata.xml_data_merge@cus", "filename": "data/com.github.darkoverlordofdata.bing-wall.appdata.xml", "type": "custom", "installed": true, "install_filename": "/usr/local/share/metainfo/com.github.darkoverlordofdata.bing-wall.appdata.xml", "build_by_default": false}, {"name": "com.github.darkoverlordofdata.bing-wall-pot", "id": "po@@com.github.darkoverlordofdata.bing-wall-pot@run", "filename": "po/com.github.darkoverlordofdata.bing-wall-pot", "type": "run", "installed": false, "build_by_default": false}, {"name": "com.github.darkoverlordofdata.bing-wall-gmo", "id": "po@@com.github.darkoverlordofdata.bing-wall-gmo@run", "filename": "po/com.github.darkoverlordofdata.bing-wall-gmo", "type": "run", "installed": false, "build_by_default": false}, {"name": "com.github.darkoverlordofdata.bing-wall-update-po", "id": "po@@com.github.darkoverlordofdata.bing-wall-update-po@run", "filename": "po/com.github.darkoverlordofdata.bing-wall-update-po", "type": "run", "installed": false, "build_by_default": false}, {"name": "as-resources_c", "id": "as-resources_c@cus", "filename": "as-resources.c", "type": "custom", "installed": false, "build_by_default": false}, {"name": "as-resources_h", "id": "as-resources_h@cus", "filename": "as-resources.h", "type": "custom", "installed": false, "build_by_default": false}, {"name": "com.github.darkoverlordofdata.bing-wall", "id": "com.github.darkoverlordofdata.bing-wall@exe", "filename": "com.github.darkoverlordofdata.bing-wall", "type": "executable", "installed": true, "install_filename": "/usr/local/bin/com.github.darkoverlordofdata.bing-wall", "build_by_default": true}]
"
2019-03-02 14:30:31,646 - Server: closing connection
2019-03-02 14:30:31,646 - CMake Wrapper: 'run'
Traceback (most recent call last):
  File "/home/bruce/.local/lib/python3.6/site-packages/mcw/cmake.py", line 59, in run
    getattr(self, self.command + '_cmd')()
  File "/home/bruce/.local/lib/python3.6/site-packages/mcw/cmake.py", line 200, in tool_cmd
    self.tool.run(self.command_args)
  File "/home/bruce/.local/lib/python3.6/site-packages/mcw/commandtool.py", line 52, in run
    getattr(self, args[0] + '_cmd')(args[1:])
  File "/home/bruce/.local/lib/python3.6/site-packages/mcw/commandtool.py", line 182, in server_cmd
    self.cmake.server.run(args)
  File "/home/bruce/.local/lib/python3.6/site-packages/mcw/server.py", line 46, in run
    getattr(self, 'handle_' + request['type'].lower())(request)
  File "/home/bruce/.local/lib/python3.6/site-packages/mcw/server.py", line 319, in handle_codemodel
    self.get_project(),
  File "/home/bruce/.local/lib/python3.6/site-packages/mcw/server.py", line 306, in get_project
    target['type'] = type_mapper[mtarget['type']]
KeyError: 'run'

**Comment by overby-me** [comment]
Sorry by delay. Should be fixed in 0.3.3. :)
