### ISSUE TITLE
CLion: borken in meson 0.50.1

### ISSUE THREAD

**Issue by BakasuraRCE** [prozum/meson-cmake-wrapper#16]
First of all sorry for the title, can't think any better.

MCW: GIT
Meson: 0.50.1
Ninja: 1.9.0
CLion: 2019.1.3
OS: Arch Linux
Project: https://github.com/hexchat/hexchat

I just followed the steps in readme and I get this:
```

/usr/bin/mcw -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" "/data/my projects/hexchat/hexchat"
Generate to build directory: /data/my projects/hexchat/hexchat/cmake-build-debug
The Meson build system
Version: 0.50.1
Source dir: /data/my projects/hexchat/hexchat
Build dir: /data/my projects/hexchat/hexchat/cmake-build-debug
Build type: native build
Project name: hexchat
Project version: 2.14.2
Native C compiler: cc (gcc 8.3.0 "cc (GCC) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.6.1)
Dependency gio-2.0 found: YES 2.60.2
Dependency gmodule-2.0 found: YES 2.60.2
Dependency openssl found: YES 1.1.1b
Checking for function "memrchr" : YES
Has header "strings.h" : YES
Checking for function "X509_get_signature_nid" with dependency openssl: YES
Checking for function "SSL_CTX_get_ssl_method" with dependency openssl: YES
Checking for function "DH_set0_pqg" with dependency openssl: YES
Checking for function "DH_get0_key" with dependency openssl: YES
Checking for function "DH_set0_key" with dependency openssl: YES
Checking for function "ERR_remove_thread_state" with dependency openssl: YES
Checking for function "ASN1_STRING_get0_data" with dependency openssl: YES
Configuring config.h using configuration
Compiler for C supports arguments -pipe: YES
Compiler for C supports arguments -fPIE: YES
Compiler for C supports arguments -funsigned-char: YES
Compiler for C supports arguments -Wno-conversion -Wconversion: YES
Compiler for C supports arguments -Wno-pointer-sign -Wpointer-sign: YES
Compiler for C supports arguments -Wno-padded -Wpadded: YES
Compiler for C supports arguments -Wno-unused-parameter -Wunused-parameter: YES
Compiler for C supports arguments -Wno-missing-prototypes -Wmissing-prototypes: YES
Compiler for C supports arguments -Winline: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Werror=implicit-function-declaration: YES
Compiler for C supports arguments -Werror=pointer-arith: YES
Compiler for C supports arguments -Werror=init-self: YES
Compiler for C supports arguments -Werror=format-security -Werror=format=1: YES
Compiler for C supports arguments -Werror=missing-include-dirs: YES
Compiler for C supports arguments -Werror=date-time: YES
Compiler for C supports arguments -fstack-protector-strong: YES
WARNING: Project targetting '>= 0.40.0' but tried to use feature introduced in '0.46.0': compiler.has_link_argument
WARNING: Project targetting '>= 0.40.0' but tried to use feature introduced in '0.46.0': compiler.has_multi_link_argument
Compiler for C supports link arguments -Wl,-z,relro: YES
Compiler for C supports link arguments -Wl,-z,now: YES
Compiler for C supports link arguments -Wl,--dynamicbase: NO
Compiler for C supports link arguments -Wl,--nxcompat: NO
Program make-te.py found: YES (/data/my projects/hexchat/hexchat/src/common/make-te.py)
Dependency libproxy-1.0 found: YES 0.4.15
Dependency libcanberra found: YES 0.30
Dependency dbus-glib-1 found: YES 0.110
WARNING: Project targetting '>= 0.40.0' but tried to use feature introduced in '0.50.0': install arg in configure_file
Configuring org.hexchat.service.service using configuration
Program dbus-binding-tool found: YES (/usr/bin/dbus-binding-tool)
Dependency gtk+-2.0 found: YES 2.24.32
Dependency x11 found: YES 1.6.7
Dependency libnotify found: YES 0.7.8
Dependency iso-codes found: YES 4.2
WARNING: Use the 'pie' kwarg instead of passing '-fpie' manually to 'hexchat'
Dependency luajit found: YES 2.0.5
Program generate_header.py found: YES (/data/my projects/hexchat/hexchat/plugins/perl/generate_header.py)
Program perl found: YES (/usr/bin/perl)
Dependency python3 found: YES 3.7
Program generate_plugin.py found: YES (/data/my projects/hexchat/hexchat/plugins/python/generate_plugin.py)
Dependency libpci found: YES 3.6.2
Configuring hexchat-plugin.pc using configuration
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Configuring io.github.Hexchat.desktop.in using configuration
Configuring io.github.Hexchat.Plugin.Checksum.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Fishlim.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Lua.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Perl.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Python.metainfo.xml using configuration
Configuring io.github.Hexchat.Plugin.Sysinfo.metainfo.xml using configuration
Configuring hexchat.1 using configuration
Program validate-textevent-translations found: YES (/data/my projects/hexchat/hexchat/po/validate-textevent-translations)
Program meson_post_install.py found: YES (/usr/bin/env python3 /data/my projects/hexchat/hexchat/meson_post_install.py)
Build targets in project: 22
WARNING: Project specifies a minimum meson_version '>= 0.40.0' but uses features which were added in newer versions:
 * 0.46.0: {'compiler.has_multi_link_argument', 'compiler.has_link_argument'}
 * 0.50.0: {'install arg in configure_file'}
Found ninja-1.9.0 at /usr/bin/ninja
Traceback (most recent call last):
  File "/usr/bin/mcw", line 11, in <module>
    load_entry_point('meson-cmake-wrapper==0.3.4', 'console_scripts', 'mcw')()
  File "/usr/lib/python3.7/site-packages/mcw/main.py", line 6, in main
    CMakeWrapper().run(sys.argv)
  File "/usr/lib/python3.7/site-packages/mcw/cmake.py", line 66, in run
    raise e
  File "/usr/lib/python3.7/site-packages/mcw/cmake.py", line 59, in run
    getattr(self, self.command + '_cmd')()
  File "/usr/lib/python3.7/site-packages/mcw/cmake.py", line 182, in generate_cmd
    self.gen_codeblocks_project()
  File "/usr/lib/python3.7/site-packages/mcw/cmake.py", line 466, in gen_codeblocks_project
    output = os.path.join(self.meson.build_dir, self.meson.get_target_filename(target))
  File "/usr/lib/python3.7/site-packages/mcw/meson.py", line 231, in get_target_filename
    return target['filename'][0]
IndexError: string index out of range
Unable to determine product file path for target checksum. Running and debugging will be unavailable.
Unable to determine product file path for target fishlim. Running and debugging will be unavailable.
Unable to determine product file path for target hexchat. Running and debugging will be unavailable.
Unable to determine product file path for target hexchat-gmo. Running and debugging will be unavailable.
Unable to determine product file path for target hexchat-perl-header. Running and debugging will be unavailable.
Unable to determine product file path for target hexchat-pot. Running and debugging will be unavailable.
Unable to determine product file path for target hexchat-update-po. Running and debugging will be unavailable.
Unable to determine product file path for target hexchatcommon. Running and debugging will be unavailable.
Unable to determine product file path for target hexchatdbus. Running and debugging will be unavailable.
Unable to determine product file path for target io.github.Hexchat.appdata.xml_data@misc_merge. Running and debugging will be unavailable.
Unable to determine product file path for target io.github.Hexchat.desktop_data@misc_merge. Running and debugging will be unavailable.
Unable to determine product file path for target lua. Running and debugging will be unavailable.
Unable to determine product file path for target marshal_c. Running and debugging will be unavailable.
Unable to determine product file path for target marshal_h. Running and debugging will be unavailable.
Unable to determine product file path for target perl. Running and debugging will be unavailable.
Unable to determine product file path for target python. Running and debugging will be unavailable.
Unable to determine product file path for target python-bindings. Running and debugging will be unavailable.
Unable to determine product file path for target remote-object-glue. Running and debugging will be unavailable.
Unable to determine product file path for target resources_c. Running and debugging will be unavailable.
Unable to determine product file path for target resources_h. Running and debugging will be unavailable.
Unable to determine product file path for target sysinfo. Running and debugging will be unavailable.
Unable to determine product file path for target textevents. Running and debugging will be unavailable.

Problems were encountered while collecting compiler information:
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/checksum/c016833@@checksum@sha: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/checksum: No such file or directory
	cc: error: projects/hexchat/hexchat/plugins/checksum: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/fishlim/c61e818@@fishlim@sha: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/fishlim: No such file or directory
	cc: error: projects/hexchat/hexchat/plugins/fishlim: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/fe-gtk/c4b29cb@@hexchat@exe: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/fe-gtk: No such file or directory
	cc: error: projects/hexchat/hexchat/src/fe-gtk: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/349de3c@@hexchatcommon@sta: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus/66b74f1@@hexchatdbus@sta: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/lua/a33201e@@lua@sha: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/lua: No such file or directory
	cc: error: projects/hexchat/hexchat/plugins/lua: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/perl/3d7dfcc@@perl@sha: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/perl: No such file or directory
	cc: error: projects/hexchat/hexchat/plugins/perl: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/python/a14715c@@python@sha: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/python: No such file or directory
	cc: error: projects/hexchat/hexchat/plugins/python: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/sysinfo/79c2f20@@sysinfo@sha: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/plugins/sysinfo: No such file or directory
	cc: error: projects/hexchat/hexchat/plugins/sysinfo: No such file or directory
	cc: error: projects/hexchat/hexchat/plugins/sysinfo/shared: No such file or directory
	cc: error: projects/hexchat/hexchat/plugins/sysinfo/unix: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug: No such file or directory
	cc: error: projects/hexchat/hexchat: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common: No such file or directory
	cc: error: projects/hexchat/hexchat/cmake-build-debug/src/common/dbus: No such file or directory
	cc: error: projects/hexchat/hexchat/src/common/dbus: No such file or directory

[Finished]
```

**Comment by overby-me** [comment]
I'm closing the issue since the project will be archived. Feel free to create a fork.
