### ISSUE TITLE
Build fails in CLion with a Type Error (meson-0.52.1)

### ISSUE THREAD

**Issue by Yamakuzure** [prozum/meson-cmake-wrapper#21]
Versions:
* Gentoo Linux, x86_64, Kernel 5.4.21
* cmake-3.16.4
* CLion 2020.1 EAP
* python-3.7.6
* meson-0.52.1 (Will try 0.53.1 later)

Here is the trace:
````
====================[ Build | pwx | Debug ]=====================================
/home/sed/.local/bin/mcw --build /home/sed/pryde_2/pwxlib/cmake-build-debug --target pwx -- -j 8
Building target: pwx
Traceback (most recent call last):
  File "/home/sed/.local/bin/mcw", line 11, in <module>
    load_entry_point('meson-cmake-wrapper==0.3.4', 'console_scripts', 'mcw')()
  File "/home/sed/.local/lib/python3.7/site-packages/mcw/main.py", line 6, in main
    CMakeWrapper().run(sys.argv)
  File "/home/sed/.local/lib/python3.7/site-packages/mcw/cmake.py", line 66, in run
    raise e
  File "/home/sed/.local/lib/python3.7/site-packages/mcw/cmake.py", line 59, in run
    getattr(self, self.command + '_cmd')()
  File "/home/sed/.local/lib/python3.7/site-packages/mcw/cmake.py", line 197, in build_cmd
    self.meson.build(self.target)
  File "/home/sed/.local/lib/python3.7/site-packages/mcw/meson.py", line 73, in build
    return self.backend.build(target)
  File "/home/sed/.local/lib/python3.7/site-packages/mcw/ninja.py", line 42, in build
    self.call(['-C', self.meson.build_dir, self.get_target(target)], True)
  File "/home/sed/.local/lib/python3.7/site-packages/mcw/ninja.py", line 17, in call
    child = subprocess.Popen([self.path] + args, stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not list
````

**Comment by Yamakuzure** [comment]
Same with meson-0.53.1

**Comment by Yamakuzure** [comment]
Simple fix:
````
--- a/mcw/ninja.py       2020-02-21 16:37:28.137028763 +0100
+++ b/mcw/ninja.py   2020-02-21 17:04:30.909921877 +0100
@@ -44,6 +44,6 @@
     def get_target(self, target_name):
         target = next((t for t in self.meson.get_targets() if t['name'] == target_name), None)
         if target:
-            return target['filename']
+            return target['filename'][0]
 
         return target_name
````

**Comment by overby-me** [comment]
This project is not maintained: #22

**Comment by Yamakuzure** [comment]
Thanks to CLion supporting Makefile targets now, which can be used to wrap meson+ninja, there is no longer a need for a meson-cmake-wrapper.
To fully work it is important, however, that ninja does verbose output, and that all calls to meson/ninja are surrounded by messages which fake GNU make entering/leaving the build directory.
A working example can be seen here:
https://github.com/elogind/elogind/blob/v246-stable/Makefile
