### ISSUE TITLE
configure the gst-build project with mcw failed

### ISSUE THREAD

**Issue by braindevices** [prozum/meson-cmake-wrapper#23]
```
Traceback (most recent call last):
  File ".local/bin/mcw", line 8, in <module>
    sys.exit(main())
  File ".local/lib/python3.8/site-packages/mcw/main.py", line 6, in main
    CMakeWrapper().run(sys.argv)
  File ".local/lib/python3.8/site-packages/mcw/cmake.py", line 66, in run
    raise e
  File ".local/lib/python3.8/site-packages/mcw/cmake.py", line 59, in run
    getattr(self, self.command + '_cmd')()
  File ".local/lib/python3.8/site-packages/mcw/cmake.py", line 182, in generate_cmd
    self.gen_codeblocks_project()
  File ".local/lib/python3.8/site-packages/mcw/cmake.py", line 466, in gen_codeblocks_project
    output = os.path.join(self.meson.build_dir, self.meson.get_target_filename(target))
  File ".local/lib/python3.8/site-packages/mcw/meson.py", line 231, in get_target_filename
    return target['filename'][0]
IndexError: string index out of range
```

**Comment by overby-me** [comment]
@braindevices I'm sorry but I don't maintain this software anymore. You can try to take a look on some of the forks that have fixed the issue.
