### ISSUE TITLE
vscode cmake-tools

### ISSUE THREAD

**Issue by agokjr** [prozum/meson-cmake-wrapper#9]
Cmake tools is using "--no-warn-unused-cli" as first argument. Which is not supported.

[proc] Executing command: C:\Users\$USER\scoop\apps\python\current\scripts\meson-cmake-wrapper --no-warn-unused-cli --help -DCMAKE_CXX_COMPILER:FILEPATH=C:\Users\$USER\scoop\apps\gcc\current\bin\x86_64-w64-mingw32-g++.exe -DCMAKE_C_COMPILER:FILEPATH=C:\Users\$USER\scoop\apps\gcc\current\bin\x86_64-w64-mingw32-gcc.exe -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -Hc:/$PROJECT_PATH -Bc:/$PROJECT_PATH/build
[cmake] Traceback (most recent call last):
[cmake]   File "c:\users\$USER\scoop\apps\python\current\lib\runpy.py", line 193, in _run_module_as_main
[cmake]     "__main__", mod_spec)
[cmake]   File "c:\users\$USER\scoop\apps\python\current\lib\runpy.py", line 85, in _run_code
[cmake]     exec(code, run_globals)
[cmake]   File "C:\Users\$USER\scoop\apps\python\current\scripts\meson-cmake-wrapper.exe\__main__.py", line 9, in <module>
[cmake]   File "c:\users\$USER\scoop\apps\python\current\lib\site-packages\mcw\main.py", line 6, in main
[cmake]     CMakeWrapper().run(sys.argv)
[cmake]   File "c:\users\$USER\scoop\apps\python\current\lib\site-packages\mcw\cmake.py", line 50, in run
[cmake]     self.parse_args(args)
[cmake]   File "c:\users\$USER\python\current\lib\site-packages\mcw\cmake.py", line 114, in parse_args
[cmake]     self.set_source_dir(args[i])
[cmake]   File "c:\users\$USER\python\current\lib\site-packages\mcw\cmake.py", line 268, in set_source_dir
[cmake]     raise RuntimeError('No such source directory: ' + source_dir)

**Comment by agokjr** [comment]
Thanks
